In [4]:
#will cover all numpy 

#why numpy --> to perform numerical calculation on fastest way , and we can do complex calculations, consumes less lib

#list tuple sets and ditcs are slow

In [3]:
#!pip install numpy
import numpy as np 

In [8]:
#create an array 
oned_array =np.array([1,2,3,4,5])
oned_array
type(oned_array)

numpy.ndarray

In [14]:
twod_array = np.array([[1,2,3,4],[5,6,7,8]])
twod_array

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [20]:
import numpy as np

threed_array = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])

print(threed_array)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [23]:
threed_array1 = np.array([
    [[23,23],[43,43]],
    [[232,334],[343,4343]],
    [[56,45],[34,343]]
    ])

In [25]:
np.array([1,2,3,4],dtype = int) # we can change type to int32,int64,bool,float

array([1, 2, 3, 4])

In [27]:
#uses of arange 
lst = []
for i in range(1,10):
    lst.append(i)
print(lst)

#use of arange 
np.arange(10)


[1, 2, 3, 4, 5, 6, 7, 8, 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#to reshape the data

data = np.arange(1,17)
data.reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
#to create a identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#np.linspace(start,stop,howmany nums we need)
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## **attributes**

In [ ]:
#to find the dimentsions  .ndim
arr = np.array([1,2,3])
arr.ndim

1

In [41]:
#shape  .shape
threed_array = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]],
    [[9,10],[11,12]]
])
threed_array.shape

(3, 2, 2)

In [52]:
arrr3 = np.arange(1,17).reshape(4,4).astype('int32')
arrr3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)

In [55]:
np.max(arrr3)#find the max value in array but to find max value in column or row we use axis

np.int32(16)

In [ ]:
#axis = 0 --> column wise
#axis = 1 --> row wise 
np.max(arrr3,axis=0) #column

array([13, 14, 15, 16], dtype=int32)

In [58]:
np.max(arrr3,axis=1)   # will samw for min 

array([ 4,  8, 12, 16], dtype=int32)

## **sum**

In [62]:
# to find the sum of array
sum = np.sum(arrr3)
print(f"sum is {sum}")

sum_row = np.sum(arrr3,axis=1)
print(sum_row)

sum is 136
[10 26 42 58]


## **product** np.prod()

In [65]:
product = np.prod(arrr3) #simiar for row and column we ad axis =0,1
product

np.int64(20922789888000)

## **stats**

In [66]:
np.mean(arrr3)

np.float64(8.5)

In [67]:
np.std(arr)

np.float64(0.816496580927726)