In [2]:
print("Gen ai task - 6  on functions by ruthvik chowdary")

Gen ai task - 6  on functions by ruthvik chowdary


In [8]:
#TASK1 
import numpy as np
one_d_arr = np.array([1,2])
one_d_arr.ndim

1

In [ ]:
two_d_arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
two_d_arr.ndim

2

In [13]:
n_arr = np.array([10,20,30,40,50])
print(n_arr.dtype)
n_arr.shape

int64


(5,)

## #task 2

In [ ]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])

addition = a+b
print(addition)

subtraction = a - b
print(subtraction)

multiplication = a*b
print(multiplication)

divison =  a/b
print(divison)

power = a ** 2
print(power)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


## #task 3

In [ ]:

values =  np.array([2,4,6,8,10])
#sqrt
np.sqrt(values)


array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766])

In [ ]:
# exponential
np.exp(values)

array([7.38905610e+00, 5.45981500e+01, 4.03428793e+02, 2.98095799e+03,
       2.20264658e+04])

In [18]:
#natural algorithm
np.log(values)

array([0.69314718, 1.38629436, 1.79175947, 2.07944154, 2.30258509])

In [19]:
#sum 
np.sum(values)

np.int64(30)

In [20]:
#cumulative sum
np.cumsum(values)

array([ 2,  6, 12, 20, 30])

## task 4

In [21]:
data = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

In [22]:
#row wise sum 
np.sum(data,axis = 1)

array([ 60, 150, 240])

In [23]:
#colum wise sum
np.sum(data,axis=0)

array([120, 150, 180])

In [24]:
#min value
np.min(values)

np.int64(2)

In [25]:
#max values
np.max(values)

np.int64(10)

In [26]:
#mean 
np.mean(values)

np.float64(6.0)

## task 5

In [27]:
marks = np.array([78,85,90,66,72,88,95,60])
#mean
np.mean(marks)

np.float64(79.25)

In [28]:
#median
np.median(marks)

np.float64(81.5)

In [29]:
#variance
np.var(marks)

np.float64(134.1875)

In [30]:
#standrad-deviation 
np.std(marks)

np.float64(11.583932838203095)

In [32]:
#max
np.max(marks)

np.int64(95)

In [33]:
#min
np.min(values)

np.int64(2)

In [34]:
np.max(marks)-np.min(marks)

np.int64(35)

## task 6 **percentiles and sorting**

In [39]:
marks = np.array([78,85,90,66,72,88,95,60])
sort_marks = np.sort(marks)
sort_marks

array([60, 66, 72, 78, 85, 88, 90, 95])

In [40]:
# to finf percentile syntax is 
#np.percentile(array,value)  value --> percent
np.percentile(marks,25)

np.float64(70.5)

In [41]:
np.percentile(marks,50)

np.float64(81.5)

In [42]:
np.percentile(marks,75)

np.float64(88.5)

In [49]:
#count the studenst above avg marks 
avg_marks = np.average(marks)
print(avg_marks)

np.mean(marks)

count = np.sum(marks > avg_marks)
count


79.25


np.int64(4)

## **mini sales analysis** on numpy 

In [50]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])
#total weekly sales
np.sum(sales)

np.int64(10700)

In [55]:
#avg daily sales
avg_sales = np.average(sales)
avg_sales

np.float64(1528.5714285714287)

In [52]:
# highest sales 
np.max(sales)

np.int64(2000)

In [53]:
#lowest of sales
np.min(sales)

np.int64(900)

In [ ]:
#standerd deviation
np.std(sales)

np.float64(345.2298849598449)

In [59]:
#sales above the average
sales[sales > avg_sales]

array([2000, 1800, 1700, 1600])